travis:
  secure:
    BINSTAR_TOKEN: WMbhdEquzsEA0G0+unMD3Bxi0Yoxn3aVNNLbJ7qZz5Io+r+7ma1E/7OOlmBHPUCGZb0I7FacKEgiR6AIZFsNS+RS8WyefFwSNbVnJYpmzeU/hP+ETMrtv/mgnTNx1YxeX7HHF5svD7DaM94RfRGCgjXfN9xhGNCbmv0XkU/d8UObu1tBQchV8dWyj8ajnguZjKJEHflqgMiFtzBLROhLw990lywV0q+UUMl7b1sq0jhO4ti/AcToPyET9RHHA+7CWqC/pjDipT30d49Evj/seJ8NBJZfUkzGvMJc2daqVRv2D83c5PIOyZu3RhTeZBQDEjm912VMNfUnCqCoUZTpreA3ofiwfDidaT6Ol3VDafqLYUBsS/hadRtA0GLfq/FuonPsAAZtDciAAhGsPIjb04xDBq+mJN0byiCkIv2U2SemY2aXrD6itSca2G67QvSid/UuDcVXmO4EEpm8bh4gaa0MSJQR7Fmn3hoyV19Q6sXel3pId3pAdo0/yv1iRf0U++EwH2T40DITUkj4a0He2mKmuuy/sYImtBa/Og/3ry2hJ5AWGCfWdxSj6wCe3Q4wI5MrCyh5kcuoQacyq/38lf9cqCAtElF12yL28X4vPWF14e1yhyr0gLVgFdWanMXAi8sVLwgaDReEb9csi5EbZYazWjMr+1Ic9bUd9Vnrc2k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
